### ISSUE TITLE
[EPS] Refatoramento de Milestone e Burndown

### ISSUE THREAD

**Issue by brunapinos** [fga-eps-mds/2018.2-Lino#100]
**Descrição**

Para manter o rastro correto de todas as sprints, assim como suas métricas, é necessário a organização das milestones e burndown de modo a refletir o projeto

**Tarefas**
 - [ ] Organizar as issues em suas respectivas milestones
 - [ ] Documentar histórias/issues como débito técnico em issues derivadas para melhor rastreio
 - [ ] Gerar burndown correto em outra ferramenta para melhor rastreio

**Critérios de Aceitação**
 - [ ] Todas as us/issues devem ser mapeadas de acordo com seu fechamento e sua respectiva sprint
 - [ ] O burndown deve ser condizente com a Sprint documentada
