### ISSUE TITLE
Incluir R2 no Roadmap

### ISSUE THREAD

**Issue by leticiadesouza** [fga-eps-mds/2018.2-Lino#183]
**Descrição**
Incluir R2 no roadmap e realizar demais edições, de modo que o documento esteja de acordo com as atualizações feitas no backlog do produto.

**Tarefas**
- [x] Remover itens referentes ao épico de monitoramento em uso.
- [x] Incluir atividades da 2ª Release. 
- [x] Atualizar atividades que envolvem os fluxos de conversas do Lino.

**Critérios de Aceitação**
- [x] Ter o Roadmap atualizado de acordo com as mudanças do escopo.
- [x] Ter 2ª Release mapeada no documento.

**Comment by icarooliv** [comment]
Uhu! It's done!
