### ISSUE TITLE
Estudar sobre os componentes interpreter e tracker do Rasa para contribuição

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#191]
**Descrição**

Esta issue tem como objetivo coletar feedbacks e anotações importantes relativas ao estudo dos componentes Interpreter e Tracker proporcionadas pelo RasaCore. O objetivo principal deste estudo é levantar a viabilidade de uma contribuição significativa para a documentação da nova versão do Rasa, logo, para realizar tal atividade, deve haver um estudo significativo em relação a esses elementos na versão mais atualizada. Com isso, levantar os pontos estudados aqui na issue e dar o veredito em relação a viabilidade de realizar uma contribuição com qualidade sem afetar o escopo do projeto (que poderá ser reduzido de acordo com o resultado do estudo).

**Tarefas**

- [ ] Estudar o código do Interpreter a fim de obter as devidas conclusões sobre os métodos contidos e sua finalidade como um componente.
- [ ] Estudar o código do Tracker a fim de obter as devidas conclusões sobre os métodos contidos e sua finalidade como um componente.
- [ ] Documentar o estudo realizado nesta issue relacionado ao Interpreter.
- [ ] Documentar o estudo realizado nesta issue relacionado ao Tracker.

**Critérios de Aceitação**

- [ ] Estudo descrito em formato de comentário nesta issue relacionado ao Interpreter.
- [ ] Estudo descrito em formato de comentário nesta issue relacionado ao Tracker.
- [ ] Veredito final da dupla em relação à possibilidade de contribuição da documentação do Rasa.

**Comment by guiaugusto** [comment]
Cadê vocês? @guilhesme23 @gabrielfilipe7unb 

Isso aqui tá pendente à um tempão AHEUAHUHAU

Tentem fazer o mais rápido possíveeeeel!

**Comment by guilhesme23** [comment]
Para facilitar o trabalho dividimos um item para cada um estudar, de forma que eu fiquei com o estudo do tracker.
Durante o estudo do código fonte encontrei alguns problemas. O código estava bem comentado e bem construído, fazendo com que não fosse muito difícil ter uma ideia do que cada método fazia, mas por ser uma versão mais atual que a que estamos usando no projeto, e essa versão muda muitas coisas que estamos fazendo, não consegui subir um bot para testar o que estava sendo estudado. Percebemos que uma única sprint era muito pouco tempo para estudar o código e tirar algo de concreto a partir de testes.

**Comment by gabrielfilipe7unb** [comment]
Fiquei com o interpreter. O código estava muito mal comentado dificultando o entendimento dos métodos envolvidos e, em consequência disso foi bem complicado prosseguir com a issue em um período de somente uma semana.

**Comment by guiaugusto** [comment]
Como vocês já deram o feedback e afirmaram a inviabilidade de execução desta tarefa, estarei fechando a issue, já que foi finalizada.
