### ISSUE TITLE
Modelar Roadmap de Produto

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Lino#63]
**Descrição**

Roadmap é tratado como uma ferramenta visual e descritiva com o intuito de mapear como será o projeto ou produto a cada período de evolução, alinhando todos os responsáveis em torno dos passos a fim de uma construção integral do produto.

**Tarefas**

- [x] Estudar o contexto geral do produto
- [x] Utilizar as histórias de usuários já definidas para mapear as histórias
- [x] Planejar outras responsabilidades para os integrantes da equipe
- [x] Organizar as atividades por Sprint
- [x] Linguagem padrão pt_BR
